#!/usr/bin/env bash
# Wrapper for launching a pi agent under systemd.
# Invoked by the unit file generated by `just service-install`.
#
# Usage: launch-agent-systemd.sh <agent-name>
#
# Behavior:
#   1. cd to the agent's folder so pi's walk-up context-file discovery finds
#      agents/<name>/AGENTS.md first, then the repo-root AGENTS.md on the way up.
#      This keeps each agent folder self-contained ("universal" — copy it elsewhere
#      and its AGENTS.md still loads).
#   2. Load agents/<name>/.env if present (per-agent secrets, provider overrides).
#   3. exec pi (no pty needed — the service is headless, no TUI to render).
#
# systemd restarts the service on crash (per the unit's Restart=always setting).
# RestartSec in the unit caps restart frequency so a broken agent doesn't burn
# CPU in a tight loop.
#
# Logs go to <repo>/logs/<name>.{out,err}.log via the unit's StandardOutput/
# StandardError settings — there is no .log pty file on Linux (that's macOS only).

set -e

AGENT="${1:?usage: $0 <agent-name>}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Run from the agent's own folder so pi's walk-up context discovery finds
# agents/<name>/AGENTS.md first, then the repo-root AGENTS.md on the way up.
# This keeps each agent folder self-contained ("universal" — copy it elsewhere
# and its AGENTS.md still loads).
cd "$REPO_ROOT/agents/$AGENT"

# Per-agent env (TELEGRAM_BOT_TOKEN, provider overrides, etc.)
if [ -f ".env" ]; then
    set -a
    . ".env"
    set +a
fi

# Per-agent config dir (so .pi/settings.json, auth, extensions are agent-specific)
export PI_CODING_AGENT_DIR="$REPO_ROOT/agents/$AGENT/.pi"

# Pre-flight: if pi isn't on PATH, fail loudly into systemd's .err.log
# instead of silently crash-looping.
if ! command -v pi >/dev/null 2>&1; then
    echo "error: 'pi' not found on PATH (PATH=$PATH)" >&2
    echo "       expected at /usr/local/bin/pi or similar" >&2
    exit 127
fi

exec pi
