#!/bin/bash
# Wrapper for launching a pi agent under launchd.
# Invoked by the LaunchAgent plist generated by `just service-install`.
#
# Usage: launch-agent.sh <agent-name>
#
# Behavior:
#   1. cd to the repo root (this script lives at <repo>/scripts/)
#   2. Load agents/<name>/.env if present (per-agent secrets, provider overrides)
#   3. exec pi inside a pty (the TUI needs one) with pty output captured to
#      logs/<name>.log
#
# launchd restarts the service on crash (per the plist's KeepAlive.Crashed
# setting). ThrottleInterval in the plist caps restart frequency so a broken
# agent doesn't burn CPU in a tight loop.

set -e

AGENT="${1:?usage: $0 <agent-name>}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Run from the agent's own folder so pi's walk-up context discovery finds
# agents/<name>/AGENTS.md first, then the repo-root AGENTS.md on the way up.
# This keeps each agent folder self-contained ("universal" — copy it elsewhere
# and its AGENTS.md still loads).
cd "$REPO_ROOT/agents/$AGENT"

# Logs stay at the repo root for consistent tailing via `just service-logs`.
mkdir -p "$REPO_ROOT/logs"

# Per-agent env (TELEGRAM_BOT_TOKEN, provider overrides, etc.)
if [ -f ".env" ]; then
    set -a
    . ".env"
    set +a
fi

# Run pi under a pty. The pty output (TUI render, agent output, errors) is
# captured to logs/<agent>.log. -F flushes after each write so the log is
# live-tailable via `just service-logs <agent>`. -q omits the "Script
# started/done" banner.
export PI_CODING_AGENT_DIR="$REPO_ROOT/agents/$AGENT/.pi"

# Pre-flight: if pi isn't on PATH, fail loudly into launchd's .err.log
# instead of silently crash-looping into the pty log.
if ! command -v pi >/dev/null 2>&1; then
    echo "error: 'pi' not found on PATH (PATH=$PATH)" >&2
    echo "       expected at /opt/homebrew/bin/pi or similar — check the plist EnvironmentVariables" >&2
    exit 127
fi

exec script -F -q "$REPO_ROOT/logs/$AGENT.log" pi
